# Generated by Django 2.2.1 on 2019-05-31 19:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190601_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 31, 19, 35, 3, 60476, tzinfo=utc)),
        ),
    ]
